#!/usr/bin/env python3
"""Append explicitly retrospective implementation detail without rewriting old entries."""
from pathlib import Path
import re
import subprocess

ticket = Path(__file__).resolve().parents[1]
repo = next(p for p in ticket.parents if (p/'queens_rollback').is_dir())
path = ticket/'reference/01-diary.md'
old = path.read_text()
assert 'Retrospective P1: executable state' not in old, 'Backfill already exists'
entries = [
dict(title='Retrospective P1: executable state and independent answer stream', commit='cf52672',
summary='This entry backfills the implementation detail behind Step 2 from the committed model, tests, and retained print receipts. It is retrospective documentation, not a newly executed implementation phase. The model made domain writes, checkpoint publication, restoration, and result acceptance independently observable before those operations were assigned clock cycles.',
did='- Added the independent recursive coordinate solver in tools/oracle.py, then the generator-based Machine in tools/queens_model.py. The oracle checks row and diagonal conflicts without domain propagation.\n- Defined Event and Fault encodings and E/C/T frames containing domains, propagation bits, pointers, outputs, and complete live records.\n- Represented output preparation as a pending state: step(False) cannot resume the generator past acceptance.\n- Retained checkpoint domain tuples in the trail model for exact restoration assertions; these are verification copies, not proposed trail hardware storage.',
why='The solution set needs an independent oracle, while the microarchitecture needs an exact state-transition specification. Separating those responsibilities reduces the chance that identical rollback mistakes in model and hardware would be accepted merely because their outputs agree.',
worked='The contemporaneous Step 2 records 16 passing model tests. The committed tests cover both storage modes, full enumeration, first-only, helper truth tables, blocked output, and reduced capacities. The checked report examples later reconfirm the complete ordered output against the independent oracle.',
failed='No model test failure is recorded. Read-only discovery found no root .gitignore or AGENTS.md; project-local ignore rules were used. The earlier diary records a whitespace rejection around quoted blank lines before the commit, but no verbatim diagnostic was retained; this backfill does not fabricate one.',
learned='A model event should describe an observable complete transition, not every future RTL state. Entering a pending output is different from accepting it. Full checkpoint comparison can be stronger than comparing only domain masks.',
tricky='The generator normally advances one event per step. Without a separate waiting flag, a blocked consumer could accidentally advance the generator into output acceptance. The implementation checks waiting and result_ready before resuming. Choice.domain snapshots remain present only as a model assertion aid.',
review='Review Machine.step, _write, frame, and the oracle separately. Confirm that the independent oracle does not import the propagation implementation and that first-only cut follows acceptance.',
validate='Historical command: python3 -m pytest sim/test_model.py -q, from queens_rollback. Inspect git show cf52672 -- queens_rollback/tools queens_rollback/sim/test_model.py.',
details='The plan receipt is 2026-09-04T21:36:06Z; P1 start is 21:36:09Z and completion 21:39:36Z. The P1 completion YAML contains literal HEAD in its QR URL. At that time the commit was cf52672, but the printed URL is mutable; the original receipt is preserved.'),
dict(title='Retrospective P2: snapshot storage and event publication',commit='0f15376',
summary='This entry expands Step 3 using the snapshot implementation commit. The original Step 3 Commit field refers to the preceding model commit cf52672, which was the available milestone while the step was written. The actual snapshot code milestone is 0f15376; this annotation corrects attribution while preserving the original chronological text.',
did='- Implemented fixed-width mask helpers and a single owner for domain and checkpoint state.\n- Stored eight 104-bit checkpoint records in the shared synchronous RAM wrapper. The low 40 bits carry metadata, and the upper 64 bits carry domains.\n- Separated checkpoint preparation, inactive-slot write, top publication, registered RAM wait, capture, and restoration.\n- Added a testbench that emits complete live checkpoint records and a Python harness comparing those records with the model.',
why='A full snapshot gives a simple recovery baseline. Using the same synchronous RAM discipline planned for trail mode avoids comparing a combinational-memory prototype against a clocked-memory implementation.',
worked='Step 3 records 23 passing combined tests: 16 model cases and seven snapshot RTL cases. The four full/first and ready/stalled combinations plus choice capacities 0, 1, and 5 exercise the baseline behavior.',
failed='No RTL compile or simulation failure is recorded. The whitespace issue from P1 was fixed in the diary helper. Subsequent print helpers resolve commit identifiers before creating QR references.',
learned='Publishing a new checkpoint top may follow an inactive RAM write. Updating remaining alternatives in an already live record must publish UPDATE on the actual write edge, or a state monitor sees an unannounced mutation.',
tricky='The shared RAM read output and controller registers both use nonblocking assignments. A controller cannot consume a newly registered read on the same edge without accounting for that scheduling. Explicit wait/capture states establish ownership of the consumed word.',
review='Review S_CP_WRITE versus S_CP_PUBLISH and S_UPDATE_WRITE. Check domain packing direction: column zero occupies the least significant domain byte. Verify that snapshot restoration installs domains and propagated bits at the same semantic boundary.',
validate='Historical command: source /home/manuel/fpga/oss-cad-suite/environment, then python3 -m pytest sim -q. Inspect git show 0f15376 and sim/test_rtl.py full C-record comparison.',
details='P2 start printed at 21:39:39Z; completion at 21:43:38Z. The completion QR points to 0f1537618c78029d0b90f1990d236488a7284f19. The implementation directly reuses symbolic_eval/rtl/sync_sdp_ram.sv without modifying it.'),
dict(title='Retrospective P3: log-before-write and reverse restoration',commit='214a39a',
summary='This entry expands Step 4 and attributes the trail implementation to 214a39a. Step 4 originally listed the preceding snapshot milestone 0f15376. The source change added recovery storage and sequencing while preserving the existing propagation algorithm, so measurements compare storage policies under the same search order.',
did='- Selected a 40-bit checkpoint RAM in trail mode and introduced 64 physical 20-bit trail slots.\n- Added S_LOG_WRITE before S_APPLY, with top publication on the domain-update edge.\n- Implemented mark checks, reverse synchronous reads, one-domain restoration, and final propagated-bitmap restoration.\n- Added logical capacities, cut-base publication, and checked backend profiling. Full-record request metrics later clarified the distinction between logical history counters and actual record widths.',
why='An old domain must be retained before a new domain becomes visible. A checkpoint mark identifies which suffix of the trail belongs to the current alternative; reverse application restores repeated writes to the same column correctly.',
worked='Step 4 records 36 passing tests. Unstalled enumeration measured 53,951 snapshot cycles and 74,523 trail cycles with 3,980 changed domain writes in each. Full outputs and live records matched the model.',
failed='No P3 compile or simulation failures are recorded. The measurements contradicted the informal expectation that a trail would necessarily reduce traffic; that was an experimental finding, not a failing test.',
learned='The live trail high-water mark is 32 and the choice high-water mark is six. A smaller checkpoint width can still lead to greater aggregate traffic because many mutations occur after a single choice. No-change writes must bypass logging, while zero-domain writes must remain reversible.',
tricky='A physically written trail slot is not live until the top advances. During reverse recovery, intermediate domains do not yet constitute a complete checkpoint; the saved propagated bitmap is installed only at RESTORED. The model asserts the complete checkpoint at that boundary.',
review='Check trail[19:17] column, [16:9] old domain, [8:4] choice level, and [3:0] zero flags. Review base <= mark <= top and capacity checks before consuming a retry alternative.',
validate='Historical command: python3 -m pytest sim -q under the CAD environment. Reproduction: ticket scripts/04-profile-backends.py; inspect backend-profile.json and source commit 214a39a.',
details='P3 start printed 21:43:41Z and completion 21:47:07Z. The completion QR points to 214a39a47d5207654330b70edc2d4ddfdc51ac34. Complete-record traffic is 672*104 bits for snapshots versus 672*40+3980*20 bits for the trail.'),
dict(title='Retrospective P4: boundaries between events, reset, and corruption',commit='1a5194f',
summary='This entry expands Step 5 and identifies 1a5194f as the boundary-verification milestone. Its original Commit field named the preceding trail commit. The additional checks examine what can happen between correct-looking event snapshots, which is where premature publication and reset ownership mistakes can otherwise remain hidden.',
did='- Added every-cycle monitors for domains, propagated bitmap, live pointers, output count, and all live RAM records when no semantic event is emitted or a fault occurs.\n- Added reset interruption during log writes, reverse application, pending output, and checkpoint writes; comparisons restart after a RESTART marker against a fresh model.\n- Injected invalid checkpoint marks, non-singleton propagation sources, and nonzero trail flags.\n- Added seeded readiness patterns, a 200-cycle first-result stall, and 64-cycle terminal dwell checks.',
why='An event-only checker could miss a mutation that appears early and is repaired before the next event. Reset tests need to verify reachability rather than physical RAM clearing. Terminal dwell checks establish that faults and cut cannot resume execution.',
worked='The contemporaneous record reports 34 RTL tests passing in 29.38 seconds. The final complete suite later includes these cases. Corrupt sources report BAD_ONEHOT; malformed marks and trail flags report TRAIL_INTEGRITY.',
failed='No P4 failures or unsuccessful repair attempts are recorded. Deliberate corruption is test stimulus, not evidence of an implementation failure.',
learned='The testbench itself changes state during corruption injection, so its stability monitor needs a narrowly bounded exemption on that injection cycle. Normal protection checks resume immediately afterward.',
tricky='Reset leaves stale RAM data physically present. Zeroed tops make it unreachable, and subsequent writes establish new ownership. Tests must compare only live entries and a fresh post-reset run, or they would incorrectly require RAM erasure.',
review='Inspect injection exemptions and terminal monitors in tb_queens.sv. Confirm that counters allowed to run during stalls are not confused with protected search state. Integrity checks detect structural inconsistencies but are not a general memory-corruption checksum.',
validate='Historical command: python3 -m pytest sim/test_rtl.py -q -x under the CAD environment. Inspect git show 1a5194f and parameterized restart/inject cases.',
details='P4 start printed 21:47:11Z and completion 21:50:24Z. Completion references 1a5194f362458600afdcd82ab16ca01e34caf264. BAD_DOMAIN_INDEX remains a reserved hardware fault because internal column fields cannot encode an index above seven.'),
dict(title='Retrospective P5: serial ownership and physical measurement provenance',commit='ca666fd',
summary='This entry expands Steps 6 and 7 from the board integration commit, hardware scripts, and archived logs. The implementation commit is ca666fd; the results package is 6c7b2d3 and the final print receipt is 4345ee4. The physical experiment verifies external records, while internal rollback trace claims remain grounded in simulation.',
did='- Added the one-record formatter, board reset integration, and UART waveform tests. The formatter retains data through the final byte and emits a terminal D or F record exactly once.\n- Ran all 58 tests, then built snapshot enumeration, trail enumeration, and trail-first with router2 seed two and the same 10 MHz constraint.\n- Armed /dev/ttyACM0 capture before each openFPGALoader invocation, observed eight seconds, and compared the complete bytes with model-generated records.\n- Archived image hashes, builds, route reports, loader output, UART binaries, profiles, and simulation first-result traces.',
why='The previous laboratory exposed a synthesis-only problem on hardware. Physical UART verification is therefore a separate evidence layer. Explicit terminal records distinguish completion from silence, and capture-before-load preserves startup output.',
worked='All eight board tests passed in 3.83s; the complete suite passed 58 tests in 51.71s. Physical snapshot and trail streams each contained 932 matching bytes, and trail-first contained 22. Routed estimates were 30.19, 30.98, and 33.72 MHz, each passing the actual 10 MHz constraint.',
failed='No synthesis, routing, loading, or physical-byte mismatch occurred. A premature status read saw no P5-hardware.exit file while work was still running; it was subsequently written as 0. P5-tests.log explicitly records the observed tool result rather than pretending to be a raw second test run.',
learned='Core acceptance is not UART completion. terminal_sent marks terminal-record selection, not final-bit delivery. nextpnr RAM_HALF and CPE subresource counts must retain their units. Wider snapshots map to more RAM halves even though their logical bit allocation is smaller.',
tricky='The serial reader must start before configuration and must not compete with another process for the UART. The benchmark excludes output stalls, whereas physical streams are UART-limited; an eight-second observation window cannot be reported as solve time.',
review='Review the LAST formatter state, reset during transmission, P5-build-commit.txt, image hashes, final rather than pre-route Fmax, and expected-versus-actual bytes. Fault and internal reset injection were simulated; they were not among the three physical images.',
validate='Inspect scripts/05-hardware.py and 06-hardware.sh. Reproduce in tmux with the CAD environment sourced and exclusive physical UART access. Read P5-hardware.json and P5-measurements.json before interpreting performance.',
details='P5 start printed 21:50:27Z and completion 22:01:44Z. The final completion QR references 6c7b2d37099830ff979416674bad0d9ffeed25d2. All eleven receipts report printed:true. The final loaded image was trail-first; repository main was pushed through 4345ee4.')
]
start = old.count('### Prompt Context') + 1
addition = ''
labels = [('What I did','did'),('Why','why'),('What worked','worked'),("What didn't work",'failed'),('What I learned','learned'),('What was tricky to build','tricky'),('What warrants a second pair of eyes','review'),('Code review instructions','validate'),('Technical details','details')]
for n,entry in enumerate(entries,start):
    info = subprocess.check_output(['git','show','-s','--format=%h — %s (%aI)',entry['commit']],cwd=repo,text=True).strip()
    addition += f"\n## Step {n}: {entry['title']}\n\n{entry['summary']}\n\n### Prompt Context\n\n"
    addition += '**User prompt (verbatim):** '+('"Backfill your diary in detail, btw."' if n==start else f'(see Step {start})')+'\n\n'
    addition += '**Assistant interpretation:** Expand the historical record from committed implementation and retained evidence; distinguish retrospective reconstruction from contemporaneous observations.\n\n**Inferred user intent:** Preserve enough detail to understand decisions, reproduce validation, and review the finished solver.\n\n'
    addition += f'**Commit (code):** {info}\n'
    for label,field in labels:
        if label == 'Code review instructions':
            addition += '\n### What should be done in the future\n\nUse this corrected commit attribution when reviewing the implementation. No new implementation work is implied by this retrospective entry.\n'
        addition += f'\n### {label}\n\n{entry[field]}\n'
path.write_text(old+addition)
print(f'Appended retrospective Steps {start}–{start+len(entries)-1}')
