import {useEffect,useRef,useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {actions,api,RootState} from './store';
import {decode,describe,display,Operation,parseImage} from './types';
import Graph from './Graph';
export default function App(){
 const {data,error:readError}=api.useStateQuery();const {data:examples}=api.useExamplesQuery();const [control,{isLoading}]=api.useControlMutation();const dispatch=useDispatch();const {selected,history}=useSelector((s:RootState)=>s.lazyView);
 const [source,setSource]=useState(''),[example,setExample]=useState('shared'),[root,setRoot]=useState(6),[ticks,setTicks]=useState(100),[error,setError]=useState(''),[heapPage,setHeapPage]=useState(0);const init=useRef(false),upload=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(examples&&!init.current){setSource(describe(examples.shared));init.current=true}},[examples]);
 if(!data)return <main className="container p-5">{readError?'Unable to read the lazy engine.':'Loading lazy graph laboratory…'}</main>;
 const frame=history?data.frames.find(f=>f.id===history)??data.current:data.current;const s=frame.snapshot;const locked=isLoading||history!==0;const viewWord=s.heap[selected];
 async function execute(operation:Operation){if(!data)return;setError('');try{await control({expectedId:data.current.id,operation}).unwrap();dispatch(actions.history(0));}catch(e){setError((e as {data?:{error?:string}}).data?.error??String(e));}}
 function load(){try{const image=parseImage(source);setRoot(image.root);dispatch(actions.select(image.root));void execute({kind:'load',image})}catch(e){setError(String(e))}}
 const download=()=>{try{parseImage(source);const u=URL.createObjectURL(new Blob([source],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download='lazy-graph.json';a.click();URL.revokeObjectURL(u)}catch(e){setError(String(e))}};
 return <><header className="lazy-header"><div><div className="eyebrow">SYMBOLIC COMPUTING / LABORATORY 04</div><h1>Lazy Graph Reducer</h1><p>Demand · shared thunks · memoized heap updates</p></div><div className="text-end"><strong className="badge text-bg-light">{s.source==='serial'?'PHYSICAL FPGA':'GO MODEL'}</strong><p className="mt-2 mb-0">{s.source==='serial'?'GateMate · 10 MHz':'Explicit continuation model'}</p><span>{s.state} · {s.counters.cycles} enabled cycles</span></div></header>
 <div className="lazy-toolbar"><button className="btn btn-dark btn-sm" disabled={locked} onClick={()=>execute({kind:'tick',ticks:1})}>Step 1 cycle</button><input className="form-control form-control-sm" aria-label="Cycles to advance" type="number" min="0" max="1000000" value={ticks} onChange={e=>setTicks(Number(e.target.value))}/><button className="btn btn-outline-dark btn-sm" disabled={locked||!Number.isInteger(ticks)||ticks<0||ticks>1000000} onClick={()=>execute({kind:'tick',ticks})}>Advance</button><span className="ms-2">root</span><input className="form-control form-control-sm" aria-label="Root address" type="number" min="0" max="1023" value={root} onChange={e=>setRoot(Number(e.target.value))}/><button className="btn btn-primary btn-sm" disabled={locked||s.state!=='idle'||!Number.isInteger(root)||root<0||root>1023} onClick={()=>execute({kind:'force',root})}>Force root</button><button className="btn btn-outline-primary btn-sm" disabled={locked||!s.valid} onClick={()=>execute({kind:'poll'})}>Poll result</button><button className="btn btn-outline-danger btn-sm" disabled={locked} onClick={()=>execute({kind:'reset'})}>Reset experiment</button></div>
 <main className="container-fluid px-3 py-3">{(error||data.needsReset)&&<div role="alert" className="alert alert-danger">{error}{data.needsReset?' Engine state uncertain; reset required.':''}</div>}{history!==0&&<div className="alert alert-info">Historical observation #{frame.id}. Controls are disabled; hardware has not been rolled back. <button className="btn btn-sm btn-outline-dark" onClick={()=>dispatch(actions.history(0))}>Return to live</button></div>}
 <div className="lazy-layout"><aside className="card"><div className="card-body"><h2>Graph image</h2><select aria-label="Example graph" className="form-select form-select-sm mb-2" disabled={locked} value={example} onChange={e=>{setExample(e.target.value);if(examples){setSource(describe(examples[e.target.value]));setRoot(examples[e.target.value].root)}}}>{Object.keys(examples??{}).map(k=><option key={k}>{k}</option>)}</select><p className="small text-secondary">Each array position is a heap address. Loading resets the experiment; forcing again retains memoized values.</p><textarea aria-label="Graph source" className="form-control lazy-source" spellCheck={false} value={source} disabled={locked} onChange={e=>setSource(e.target.value)}/><button className="btn btn-primary btn-sm w-100 mt-2" disabled={locked} onClick={load}>Load graph</button><div className="d-flex gap-2 mt-2"><button className="btn btn-outline-secondary btn-sm" disabled={locked} onClick={()=>upload.current?.click()}>Import JSON</button><button className="btn btn-outline-secondary btn-sm" onClick={download}>Export JSON</button><input ref={upload} hidden type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(f){if(f.size>128*1024){setError('Image exceeds 128 KiB.');return}setSource(await f.text());e.target.value=''}}}/></div><hr/><h2>Selected node @{selected}</h2>{viewWord!==undefined?<><strong>{display(viewWord)}</strong><p className="font-monospace small mt-2">0x{viewWord.toString(16).padStart(10,'0')}</p>{decode(viewWord).tag===5&&<p className="small">Claimed by evaluator 0. An UPDATE continuation must install the value or error.</p>}</>:<p>No allocated node selected.</p>}</div></aside>
 <section><div className="card mb-3"><div className="card-body"><div className="d-flex justify-content-between"><h2>Live heap references</h2><span className="small text-secondary">{s.heap.length} / 1024 words · {s.stack.length} / 512 frames</span></div><Graph snapshot={s} selected={selected} onSelect={n=>dispatch(actions.select(n))}/></div></div>
 <div className={`alert ${s.valid?(decode(s.result).tag===13?'alert-danger':'alert-success'):'alert-secondary'}`}><strong>{s.valid?`Offered result: ${display(s.result)}`:`Evaluator: ${s.state}`}</strong><div className="small">{s.valid?'Result remains stable until Poll. A later Force reuses the heap.':'Force a root, then advance cycles. Paused state retains claims and continuations.'}</div></div>
 <div className="card mb-3"><div className="card-body"><h2>Continuation stack</h2><p className="small text-secondary">Top first · explicit unfinished evaluation · saved values are full 40-bit words</p>{s.stack.length===0?<p className="text-secondary">No outstanding continuations.</p>:<div className="table-responsive lazy-scroll"><table className="table table-sm"><thead><tr><th>Depth</th><th>Frame</th><th>Resume information</th></tr></thead><tbody>{s.stack.map((_,i)=>{const n=s.stack.length-1-i,f=s.stack[n];return <tr key={n}><td>{n}</td><td>{['','EVAL_RIGHT','APPLY','UPDATE'][f.kind]}</td><td>{f.kind===3?`memoize @${f.address}`:f.kind===1?`${f.op===1?'ADD':'MUL'} · right @${f.address}`:`${f.op===1?'ADD':'MUL'} · left ${display(f.value)}`}</td></tr>})}</tbody></table></div>}</div></div>
 <div className="card"><div className="card-body"><h2>Heap mutation trace</h2><p className="small text-secondary">{s.trace.length} / 64 records · {s.dropped} dropped · old and new nodes are observed values</p>{s.dropped>0&&<div className="alert alert-warning">Trace incomplete: {s.dropped} mutations were not retained.</div>}<div className="table-responsive lazy-scroll"><table className="table table-sm"><thead><tr><th>Cycle</th><th>Address</th><th>Before</th><th>After</th></tr></thead><tbody>{s.trace.map((e,n)=><tr key={n} className={e.address===selected?'table-info':''}><td>{e.cycle}</td><td><button className="btn btn-link btn-sm p-0" onClick={()=>dispatch(actions.select(e.address))}>@{e.address}</button></td><td>{display(e.old)}</td><td>{display(e.new)}</td></tr>)}</tbody></table></div></div></div></section>
 <aside><div className="card mb-3"><div className="card-body"><h2>Execution counters</h2><dl className="lazy-metrics">{Object.entries(s.counters).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="small text-secondary">Shared example: one claim, one update, one multiplication, result 168.</p></div></div><div className="card mb-3"><div className="card-body"><h2>Snapshot history</h2><select aria-label="Snapshot history" className="form-select form-select-sm" value={history} onChange={e=>dispatch(actions.history(Number(e.target.value)))}><option value={0}>Live state</option>{data.frames.map(f=><option key={f.id} value={f.id}>#{f.id} · {f.label} · cycle {f.snapshot.counters.cycles}</option>)}</select><p className="small text-secondary mt-2">Up to 128 operation boundaries. A batch of ticks is one observation, not a frame per cycle.</p></div></div><div className="card"><div className="card-body"><h2>Polled results</h2>{data.results.length?data.results.map((v,n)=><div className="font-monospace small mb-2" key={n}>{display(v)}</div>):<p className="text-secondary">No result consumed yet.</p>}</div></div></aside></div>
 <section className="card mt-3"><div className="card-body"><div className="d-flex gap-3 align-items-center"><h2 className="mb-0">Heap words</h2><button className="btn btn-sm btn-outline-secondary" disabled={heapPage===0} onClick={()=>setHeapPage(Math.max(0,heapPage-1))}>Previous</button><button className="btn btn-sm btn-outline-secondary" disabled={(heapPage+1)*32>=s.heap.length} onClick={()=>setHeapPage(heapPage+1)}>Next</button></div><div className="table-responsive"><table className="table table-sm mt-2"><thead><tr><th>Address</th><th>Node</th><th>Raw 40-bit word</th></tr></thead><tbody>{s.heap.slice(heapPage*32,heapPage*32+32).map((w,i)=><tr key={i} className={selected===heapPage*32+i?'table-info':''}><td><button className="btn btn-link btn-sm p-0" onClick={()=>dispatch(actions.select(heapPage*32+i))}>@{heapPage*32+i}</button></td><td>{display(w)}</td><td className="font-monospace">{w.toString(16).padStart(10,'0')}</td></tr>)}</tbody></table></div></div></section></main></>;
}
