export type Image={nodes:number[];root:number};
export type Continuation={kind:number;op:number;address:number;value:number};
export type Mutation={cycle:number;address:number;old:number;new:number};
export type Snapshot={source:string;state:string;address:number;result:number;valid:boolean;heap:number[];stack:Continuation[];counters:Record<string,number>;trace:Mutation[];dropped:number};
export type Frame={id:number;label:string;snapshot:Snapshot};
export type State={current:Frame;frames:Frame[];results:number[];needsReset:boolean};
export type Operation={kind:string;image?:Image;root?:number;ticks?:number};
export const tags:Record<number,string>={0:'INT',1:'ADD',2:'MUL',3:'THUNK',4:'IND',5:'BLACKHOLE',13:'ERROR',15:'FREE'};
export const faults:Record<number,string>={1:'HEAP_ADDRESS',2:'CONTINUATION_OVERFLOW',3:'CYCLIC_THUNK',4:'INDIRECTION_CYCLE',5:'TYPE_FAULT',6:'ARITHMETIC_OVERFLOW',7:'OWNERSHIP_FAULT'};
export function decode(word:number){const tag=Math.floor(word/2**36);const payload=word%2**32;return{tag,name:tags[tag]??'INVALID',a:Math.floor(payload/65536),b:payload%65536,value:payload>=2**31?payload-2**32:payload,payload};}
export function display(word:number){const w=decode(word);return w.tag===0?`INT(${w.value})`:w.tag===13?`ERROR(${faults[w.payload]??w.payload})`:w.tag===1||w.tag===2?`${w.name} @${w.a}, @${w.b}`:w.tag===3||w.tag===4?`${w.name} @${w.a}`:w.name;}
export function describe(image:Image){return JSON.stringify({root:image.root,nodes:image.nodes.map(word=>{const w=decode(word);return w.tag===0?{tag:w.name,value:w.value}:w.tag===13?{tag:w.name,code:w.payload}:w.tag===1||w.tag===2?{tag:w.name,a:w.a,b:w.b}:w.tag===3||w.tag===4?{tag:w.name,a:w.a}:{tag:w.name}})},null,2);}
export function parseImage(source:string):Image{const data=JSON.parse(source);if(!Array.isArray(data.nodes)||data.nodes.length<1||data.nodes.length>1024||!Number.isInteger(data.root)||data.root<0||data.root>=data.nodes.length)throw Error('Use 1–1024 nodes and an in-range root.');const integer=(v:unknown,min:number,max:number)=>{if(typeof v!=='number'||!Number.isInteger(v)||v<min||v>max)throw Error(`Expected integer ${min}…${max}.`);return v;};const nodes=data.nodes.map((n:{tag:string;value?:number;a?:number;b?:number;code?:number})=>{const tag=Object.entries(tags).find(([,v])=>v===n.tag)?.[0];if(tag===undefined||tag==='5')throw Error('Unknown tag or externally supplied BLACKHOLE.');const t=Number(tag);const allowed=t===0?['tag','value']:t===13?['tag','code']:[1,2].includes(t)?['tag','a','b']:[3,4].includes(t)?['tag','a']:['tag'];if(Object.keys(n).some(k=>!allowed.includes(k)))throw Error('Unexpected node field.');let payload=0;if(t===0){const v=integer(n.value,-(2**31),2**31-1);payload=v<0?v+2**32:v;}else if(t===13)payload=integer(n.code,0,2**32-1);else if([1,2,3,4].includes(t))payload=integer(n.a,0,65535)*65536+([1,2].includes(t)?integer(n.b,0,65535):0);return t*2**36+payload;});return{nodes,root:data.root};}
