from pathlib import Path
p=Path('pkg/dataflow/transaction.go');s=p.read_text().replace('type Transaction struct {','type Transaction struct {\n Debug DebugSnapshot')
s=s.replace('return &Transaction{Config: c,','return &Transaction{Debug: DebugSnapshot{Node:255,Context:255,Events:[]DebugEvent{}}, Config: c,')
s=s.replace('m.pendingError[c] = nil\n\treturn true','m.pendingError[c] = nil\n m.debugEvent(EventCancel,Token{Context:c,Epoch:m.Epoch[c]})\n\treturn true')
s=s.replace('m.Metrics.StaleOutput++','m.Metrics.StaleOutput++\n m.debugEvent(EventStale,t)')
s=s.replace('\t\treturn &t\n','\t\tm.debugEvent(EventOutput,t)\n\t\treturn &t\n',1)
s=s.replace('m.Metrics.StaleInput++','m.Metrics.StaleInput++\n m.debugEvent(EventStale,t)')
s=s.replace('m.fail(t, code)\n\t}\n}', 'm.fail(t, code)\n } else {m.debugEvent(EventOperand,t)}\n}',1)
s=s.replace('m.Metrics.StaleRouter++','m.Metrics.StaleRouter++\n m.debugEvent(EventStale,t)')
s=s.replace('r.Delivered |= 1 << i','m.debugEvent(EventRoute,Token{Context:t.Context,Epoch:t.Epoch,Node:dest.Node,Port:dest.Port,Producer:t.Producer,Value:t.Value})\n\t\tr.Delivered |= 1 << i')
s=s.replace('m.Metrics.Cycles++','if m.Debug.Halted{return nil}\n m.Metrics.Cycles++\n defer func(){if m.Debug.Mask&2!=0&&len(m.completed)==m.Config.CompletionDepth{m.halt(2)}}()',1)
s=s.replace('m.Metrics.StaleCompletion++','m.Metrics.StaleCompletion++\n m.debugEvent(EventStale,*t)')
s=s.replace('m.completed = append(m.completed, *t)','m.completed = append(m.completed, *t)\n m.debugEvent(EventCompletion,*t)')
s=s.replace('m.Metrics.StaleIssue++','m.Metrics.StaleIssue++\n m.debugEvent(EventStale,m.completion(i.Context,i.Epoch,i.Node,0))')
s=s.replace('m.Metrics.Activations++','m.Metrics.Activations++\n m.debugEvent(EventIssue,t)')
p.write_text(s)
p=Path('pkg/dataflow/engine.go');s=p.read_text().replace('type Operation struct {','type Operation struct {\n Debug *DebugControl `json:"debug,omitempty"`')
s=s.replace('switch o.Kind {','switch o.Kind {\n case "debug":\n if o.Debug==nil{return errors.New("debug requires control")};return o.Debug.Validate()',1)
s=s.replace('type Snapshot struct {','type Snapshot struct {\n Debug DebugSnapshot `json:"debug"`')
pos=s.index('func (m *Transaction) Execute');s=s[:pos]+s[pos:].replace('switch o.Kind {','switch o.Kind {\n case "debug":\n m.debugControl(*o.Debug)',1)
s=s.replace('for i := uint32(0); i < o.Ticks; i++ {','for i := uint32(0); i < o.Ticks && !m.Debug.Halted; i++ {')
s=s.replace('s := Snapshot{Graph:', 's := Snapshot{Debug:m.Debug.Clone(), Graph:')
s=s.replace('func (s Snapshot) Clone() Snapshot {','func (s Snapshot) Clone() Snapshot {\n s.Debug=s.Debug.Clone()')
p.write_text(s)
