import {useEffect,useRef,useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {actions,api,type AppDispatch,type RootState} from './store';
import {Graph} from './Graph';
import {Inspector,Pipelines} from './Inspectors';
import {intValue,valueText,type Config,type Operation,type Validation} from './types';
function errorText(error:unknown):string{if(error&&typeof error==='object'&&'data' in error){const data=error.data;if(data&&typeof data==='object'&&'error' in data)return String(data.error)}return error instanceof Error?error.message:'Request failed. Refresh the live state.'}
export default function App(){
 const dispatch=useDispatch<AppDispatch>();const workspace=useSelector((s:RootState)=>s.workspace);
 const {data:state,error:stateError}=api.useStateQuery(undefined,{pollingInterval:300});
 const {data:examples}=api.useExamplesQuery();const {data:projects=[]}=api.useProjectsQuery();
 const {currentData:historical,error:historyError}=api.useHistoryQuery(workspace.history??{id:0,generation:0},{skip:!workspace.history});
 const [control,{isLoading:controlling}]=api.useControlMutation();const [run,{isLoading:starting}]=api.useRunMutation();const [pause]=api.usePauseMutation();
 const [validate]=api.useValidateMutation();const [save,{isLoading:saving}]=api.useSaveMutation();const [loadProject]=api.useLazyProjectQuery();
 const [validation,setValidation]=useState<Validation|null>(null);const [notice,setNotice]=useState('');const [error,setError]=useState('');
 const [projectID,setProjectID]=useState('my-expression');const [savedSource,setSavedSource]=useState('');const [ticks,setTicks]=useState(16);
 const [rawNode,setRawNode]=useState(0);const [rawPort,setRawPort]=useState(0);const [rawValue,setRawValue]=useState('7');const [rawTag,setRawTag]=useState('INT');
 const [config,setConfig]=useState<Config>({InputDepth:8,CompletionDepth:8,OutputDepth:8,MulLatency:4,EpochBits:8});
 const fileInput=useRef<HTMLInputElement>(null);const initialized=useRef(false);
 useEffect(()=>{if(examples&&!initialized.current){initialized.current=true;if(!workspace.source)dispatch(actions.setSource(examples.book))}},[examples,workspace.source,dispatch]);
 useEffect(()=>{setValidation(null);let current=true;const timer=setTimeout(()=>{if(workspace.source)validate(workspace.source).unwrap().then(v=>{if(current)setValidation(v)}).catch(e=>{if(current)setError(errorText(e))})},250);return()=>{current=false;clearTimeout(timer)}},[workspace.source,validate]);
 const frame=workspace.history?historical:state?.current;const snapshot=frame?.snapshot;
 const historicalMode=workspace.history!==null;const busy=controlling||starting||Boolean(state?.running);
 const locked=busy||historicalMode;const invalid=!validation||validation.diagnostics.length>0;
 async function invoke(operation:Operation){if(!state)return;setError('');setNotice('');try{await control({expectedId:state.current.id,operation}).unwrap()}catch(e){setError(errorText(e))}}
 async function execute(mode:'step'|'run'){if(!state)return;setError('');setNotice('');try{await run({source:workspace.source,mode,expectedId:state.current.id}).unwrap()}catch(e){setError(errorText(e))}}
 async function saveSource(){setError('');try{await save({id:projectID,source:workspace.source}).unwrap();setSavedSource(workspace.source);setNotice(`Saved ${projectID}`)}catch(e){setError(errorText(e))}}
 async function openProject(id:string){if(!id)return;setError('');try{const result=await loadProject(id,false).unwrap();dispatch(actions.setSource(result.source));setProjectID(id);setSavedSource(result.source);setNotice(`Opened ${id}`)}catch(e){setError(errorText(e))}}
 function exportSource(){const url=URL.createObjectURL(new Blob([workspace.source],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`${projectID||'scenario'}.json`;a.click();URL.revokeObjectURL(url)}
 async function importSource(file:File|undefined){if(!file)return;if(file.size>128*1024){setError('Source exceeds 128 KiB');return}dispatch(actions.setSource(await file.text()));setNotice(`Imported ${file.name}`)}
 async function inject(){if(!snapshot)return;try{const n=Number(rawValue);const value=rawTag==='BOOL'?(2**36+(n?1:0)):intValue(n);await invoke({kind:'inject',token:{context:workspace.context,epoch:snapshot.epochs[workspace.context],node:rawNode,port:rawPort,final:false,producer:255,subtype:0,value}})}catch(e){setError(errorText(e))}}
 return <div className="df-app">
  <header className="df-header"><div><div className="df-overline">SYMBOLIC COMPUTING / LABORATORY 03</div><h1>Elastic Dataflow</h1><p>Scenario editor · execution debugger · FPGA instrument</p></div><div className="df-session-badges"><span className={`df-source ${snapshot?.source==='serial'?'hardware':''}`}>{!snapshot?'CONNECTING':snapshot.source==='serial'?'PHYSICAL FPGA':'TRANSACTION MODEL'}</span><span>{!snapshot?'Awaiting engine snapshot':snapshot.source==='serial'?'GateMate · 10 MHz':'Software reference · explicit cycles'}</span><span className="df-connection">{stateError?'API disconnected':state?.running?'Scenario running':snapshot?.quiescent?'Paused · drained':'Paused · work retained'}</span></div></header>
  <div className="df-toolbar"><div className="btn-group"><button className="btn btn-dark" disabled={locked||!state||state.needsReset} onClick={()=>void invoke({kind:'tick',ticks:1})}>Step 1 cycle</button><button className="btn btn-outline-dark" disabled={locked||!state||state.needsReset} onClick={()=>void invoke({kind:'tick',ticks})}>Advance</button></div><input aria-label="Cycles to advance" className="form-control df-ticks" type="number" min="0" max="1000000" value={ticks} onChange={e=>setTicks(Math.max(0,Math.min(1000000,Number(e.target.value))))}/><span className="small text-secondary">cycles</span>
   <button className="btn btn-outline-dark" disabled={locked||!state||state.needsReset} onClick={()=>void invoke({kind:'poll'})}>Poll result</button><button className="btn btn-outline-danger" disabled={locked||!state||state.needsReset} onClick={()=>void invoke({kind:'cancel',context:workspace.context})}>Cancel C{workspace.context}</button><button className="btn btn-outline-secondary" disabled={locked||!state} onClick={()=>void invoke({kind:'reset'})}>Reset engine</button>
   <div className="df-cycle"><strong>{frame?.cycle??0}</strong><span>ENABLED CYCLES</span></div>
  </div>
  {(error||stateError||state?.error||state?.needsReset)&&<div className="alert alert-danger mx-3 mt-3 mb-0" role="alert">{error||state?.error||(stateError?'Cannot reach the dataflow API.':'')}{state?.needsReset&&<strong> Last snapshot only. Reset is required before further execution.</strong>}</div>}
  {notice&&<div className="alert alert-success mx-3 mt-3 mb-0" role="status">{notice}</div>}
  {historicalMode&&<div className="df-history-banner"><strong>HISTORICAL SNAPSHOT {workspace.history?.id}</strong><span>{historyError?'This frame has expired.':frame?.label??'Loading frame…'} · controls are disabled</span><button className="btn btn-sm btn-dark" onClick={()=>dispatch(actions.setHistory(null))}>Return to live</button></div>}
  <main className="df-workspace">
   <aside className="df-panel df-editor"><div className="df-panel-heading"><h2>Scenario source</h2><span>{workspace.source===savedSource?'saved':'edited'}</span></div>
    <label className="form-label small" htmlFor="example">EXAMPLE</label><select id="example" className="form-select form-select-sm mb-2" defaultValue="book" onChange={e=>{if(examples)dispatch(actions.setSource(examples[e.target.value]))}}>{Object.keys(examples??{book:''}).map(id=><option key={id} value={id}>{id==='book'?'Interleaved expressions':id==='cancel'?'In-flight cancellation':id==='copy'?'COPY fanout':'Isolated fault'}</option>)}</select>
    <div className="df-editor-actions"><button className="btn btn-sm btn-outline-secondary" disabled={invalid} onClick={()=>validation&&dispatch(actions.setSource(validation.formatted))}>Format</button><button className="btn btn-sm btn-outline-secondary" onClick={()=>fileInput.current?.click()}>Import</button><button className="btn btn-sm btn-outline-secondary" onClick={exportSource}>Export</button><input ref={fileInput} className="d-none" type="file" accept=".json,application/json" onChange={e=>void importSource(e.target.files?.[0])}/></div>
    <textarea aria-label="Scenario JSON source" spellCheck={false} className="df-source-editor" value={workspace.source} onChange={e=>dispatch(actions.setSource(e.target.value))} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();if(!locked&&!invalid)void execute('run')}if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();if(!invalid)void saveSource()}}}/>
    <div className={`df-validation ${invalid?'invalid':'valid'}`} aria-live="polite">{!validation?'Validating…':validation.diagnostics.length?validation.diagnostics.map((d,i)=><p key={i}>{d.action>=0?`Action ${d.action+1}: `:''}{d.message}</p>):`${validation.actions} actions · valid scenario`}</div>
    <div className="df-run-actions"><button className="btn btn-primary" disabled={locked||invalid||!state} onClick={()=>void execute('run')}>Run from start</button><button className="btn btn-outline-primary" disabled={locked||invalid||!state} onClick={()=>void execute('step')}>Next action</button><button className="btn btn-outline-danger" disabled={!state?.running} onClick={()=>void pause().unwrap().catch(e=>setError(errorText(e)))}>Pause</button></div>
    <p className="small text-secondary mt-2">Action {state?.step??0} / {state?.actions??0} · Run begins with the source reset. Next action continues this source.</p>
    <div className="df-project-save"><input aria-label="Project ID" className="form-control form-control-sm" value={projectID} onChange={e=>setProjectID(e.target.value)}/><button className="btn btn-sm btn-dark" disabled={saving||invalid} onClick={()=>void saveSource()}>Save</button></div>
    <select aria-label="Open saved project" className="form-select form-select-sm mt-2" value="" onChange={e=>void openProject(e.target.value)}><option value="">Open saved project…</option>{projects.map(id=><option key={id}>{id}</option>)}</select>
    {snapshot?.source==='model'&&<details className="df-config"><summary>Model configuration</summary>{(Object.keys(config) as (keyof Config)[]).map(key=><label key={key}>{key}<select value={config[key]} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})}>{(key==='EpochBits'?[2,8]:key==='MulLatency'?[1,2,4,8]:[1,2,8]).map(v=><option key={v}>{v}</option>)}</select></label>)}<button className="btn btn-sm btn-outline-dark mt-2" disabled={locked} onClick={()=>void invoke({kind:'reset',config})}>Reset with configuration</button></details>}
   </aside>
   <div className="df-center">{snapshot?<>
    <section className="df-panel"><div className="df-panel-heading"><h2>Expression graph</h2><span>a × b + c × d + int(e &lt; f)</span></div><div className="df-contexts">{snapshot.epochs.map((epoch,c)=><button key={c} className={`df-context ${workspace.context===c?'active':''}`} onClick={()=>dispatch(actions.setContext(c))}><strong>C{c}</strong><span>epoch {epoch}</span><small>{snapshot.closed[c]?'closed':'open'}</small></button>)}</div><Graph snapshot={snapshot} context={workspace.context} selected={workspace.node} onSelect={n=>dispatch(actions.setNode(n))}/><div className="df-legend"><span className="ready">ready</span><span className="executing">executing</span><span className="issued">issued once</span><span className="waiting">waiting for operand</span></div></section>
    <Pipelines snapshot={snapshot}/>
    <section className="df-panel"><div className="df-panel-heading"><h2>Snapshot history</h2><span>{state?.history.length??0} / 128 boundaries retained</span></div><select aria-label="Snapshot history" className="form-select form-select-sm" value={workspace.history?.id??''} onChange={e=>{const f=state?.history.find(f=>f.id===Number(e.target.value));dispatch(actions.setHistory(f?{id:f.id,generation:f.generation}:null))}}><option value="">Live state</option>{state?.history.map(f=><option key={f.id} value={f.id}>#{f.id} · cycle {f.cycle} · {f.label}</option>)}</select><div className="df-history-strip">{state?.history.slice(-12).map(f=><button key={f.id} className={workspace.history?.id===f.id?'active':''} onClick={()=>dispatch(actions.setHistory({id:f.id,generation:f.generation}))}><strong>{f.cycle}</strong><span>#{f.id}</span></button>)}</div><p className="small text-secondary mb-0">Each frame is a complete operation-boundary snapshot. Batched ticks do not imply a frame for every internal cycle.</p></section>
   </>:<div className="df-panel p-4">{historicalMode?'Select Return to live to continue.':'Connecting to the dataflow engine…'}</div>}</div>
   <aside className="df-right">{snapshot&&<><Inspector snapshot={snapshot} context={workspace.context} node={workspace.node}/><section className="df-panel"><div className="df-panel-heading"><h2>Inject operand</h2><span>C{workspace.context} / E{snapshot.epochs[workspace.context]}</span></div><div className="df-inject-grid"><label>Node<select className="form-select form-select-sm" value={rawNode} onChange={e=>setRawNode(Number(e.target.value))}>{[0,1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><label>Port<select className="form-select form-select-sm" value={rawPort} onChange={e=>setRawPort(Number(e.target.value))}><option value="0">A</option><option value="1">B</option></select></label><label>Type<select className="form-select form-select-sm" value={rawTag} onChange={e=>setRawTag(e.target.value)}><option>INT</option><option>BOOL</option></select></label><label>Payload<input className="form-control form-control-sm" value={rawValue} onChange={e=>setRawValue(e.target.value)}/></label></div><button className="btn btn-sm btn-outline-dark mt-2 w-100" disabled={locked||state?.needsReset} onClick={()=>void inject()}>Inject into input queue</button></section></>}</aside>
  </main>
  {snapshot&&<section className="df-bottom"><div className="df-panel"><div className="df-panel-heading"><h2>Session results</h2><span>consumed through Poll</span></div><table className="table table-sm"><thead><tr><th>Context</th><th>Epoch</th><th>Value</th><th>Type</th></tr></thead><tbody>{state?.results.map((r,i)=><tr key={i}><td>C{r.context}</td><td>{r.epoch}</td><td className="df-result-value">{valueText(r.value)}</td><td>{r.subtype?`fault ${r.subtype}`:'final INT'}</td></tr>)}</tbody></table>{!state?.results.length&&<p className="small text-secondary">No results consumed yet. Tick the engine, then poll.</p>}</div>
   <div className="df-panel"><div className="df-panel-heading"><h2>Engine counters</h2><span>{snapshot.source}</span></div><div className="df-counters">{Object.entries(snapshot.counters).map(([key,v])=><div key={key}><strong>{v}</strong><span>{key}</span></div>)}</div></div>
   <div className="df-panel"><div className="df-panel-heading"><h2>Execution console</h2><span>session events</span></div><div className="df-console">{state?.events.slice(-8).reverse().map((e,i)=><div key={`${e.at}-${i}`} className={e.error?'error':''}><strong>{e.label}</strong><span>{e.detail}</span></div>)}</div></div>
  </section>}
  <footer className="df-footer">Fixed graph / 4 contexts / typed 40-bit values / 80-bit tokens <span>GATEMATE-SYMBOLIC-007 · snapshot generation {frame?.generation??0}</span></footer>
 </div>
}
