import {useEffect,useRef,useState} from 'react';
import {useDispatch,useSelector} from 'react-redux';
import {actions,api,type RootState,type AppDispatch} from './store';
import {valueText,type Frame,type State,type Program,type Snapshot,type Operation} from './types';
const message=(e:unknown)=>{if(e&&typeof e==='object'&&'data'in e)return JSON.stringify(e.data);return String(e)};
export function ProgramEditor({state,frame,locked}:{state:State|undefined;frame:Frame|undefined;locked:boolean}){
 const dispatch=useDispatch<AppDispatch>();const source=useSelector((s:RootState)=>s.workspace.programSource);const context=useSelector((s:RootState)=>s.workspace.context);
 const [compile,{isLoading:compiling}]=api.useCompileMutation();const [load,{isLoading:loading}]=api.useLoadProgramMutation();const [inject,{isLoading:injecting}]=api.useProgramInputsMutation();
 const [save]=api.useSaveProgramMutation();const [open]=api.useLazyProgramQuery();const {data:programs=[]}=api.useProgramsQuery();
 const [compiled,setCompiled]=useState<Program|null>(null);const [diagnostics,setDiagnostics]=useState<string[]>([]);const [error,setError]=useState('');const [notice,setNotice]=useState('');
 const [values,setValues]=useState<Record<string,string>>({});const [id,setID]=useState('my-program');const file=useRef<HTMLInputElement>(null);
 const loaded=frame?.program;const current=compiled?.source===source?compiled:null;const disabled=locked||loading||injecting||Boolean(state?.needsReset);
 useEffect(()=>{setValues(Object.fromEntries((loaded?.inputs??[]).map((v,n)=>[v.name,v.type==='bool'?'1':String(n+3)])))},[loaded?.source]);
 async function doCompile(){setError('');setNotice('');try{const result=await compile(source).unwrap();setCompiled(result.program);setDiagnostics(result.diagnostics)}catch(e){setError(message(e))}}
 async function doLoad(){if(!state)return;setError('');try{await load({source,expectedId:state.current.id}).unwrap();dispatch(actions.setNode(0));setNotice('Program loaded and descriptor readback verified.')}catch(e){setError(message(e))}}
 async function supply(){if(!state)return;setError('');try{const numbers=Object.fromEntries(Object.entries(values).map(([k,v])=>{if(!v.trim()||!Number.isSafeInteger(Number(v)))throw new Error(`Input ${k} must be an integer`);return[k,Number(v)]}));await inject({expectedId:state.current.id,context,values:numbers}).unwrap()}catch(e){setError(message(e))}}
 function exportSource(){const url=URL.createObjectURL(new Blob([source],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${id||'program'}.df`;a.click();URL.revokeObjectURL(url)}
 async function importSource(f:File|undefined){if(!f)return;if(f.size>128*1024){setError('Source exceeds 128 KiB');return}dispatch(actions.setProgramSource(await f.text()));setCompiled(null);setDiagnostics([])}
 return <div className="df-program-editor"><div className="df-panel-heading"><h2>Typed program</h2><span>{current?`${current.graph.count} / 7 nodes`:'draft'}</span></div>
 <p className="small text-secondary">Declare typed inputs, name intermediate values, and select one output. Compile checks the graph; Load resets the engine.</p>
 <textarea className="df-source-editor df-program-source" aria-label="Typed program source" spellCheck={false} value={source} onChange={e=>{dispatch(actions.setProgramSource(e.target.value));setDiagnostics([])}}/>
 <div className="df-run-actions"><button className="btn btn-primary" disabled={compiling} onClick={()=>void doCompile()}>Compile program</button><button className="btn btn-dark" disabled={disabled||!current||!state} onClick={()=>void doLoad()}>Load program</button></div>
 {diagnostics.length>0&&<div className="alert alert-danger small mt-2" role="alert">{diagnostics.map((d,n)=><p key={n} className="mb-0">{d}</p>)}</div>}
 {current&&<p className="small text-success mt-2">Compiled · {current.inputs.length} inputs · {current.graph.count} nodes · one final output</p>}
 {error&&<div className="alert alert-danger small mt-2" role="alert">{error}</div>}{notice&&<p className="small text-success mt-2" role="status">{notice}</p>}
 <div className="df-editor-actions mt-2"><button className="btn btn-sm btn-outline-secondary" onClick={()=>file.current?.click()}>Import .df</button><button className="btn btn-sm btn-outline-secondary" onClick={exportSource}>Export .df</button><input className="d-none" ref={file} type="file" accept=".df,.txt" onChange={e=>void importSource(e.target.files?.[0])}/></div>
 <div className="df-project-save mt-2"><input aria-label="Program ID" className="form-control form-control-sm" value={id} onChange={e=>setID(e.target.value)}/><button className="btn btn-sm btn-outline-dark" disabled={!current} onClick={()=>void save({id,source}).unwrap().then(()=>setNotice(`Saved ${id}.df`)).catch(e=>setError(message(e)))}>Save program</button></div>
 <select aria-label="Open saved program" className="form-select form-select-sm mt-2" value="" onChange={e=>{if(e.target.value)void open(e.target.value,false).unwrap().then(r=>dispatch(actions.setProgramSource(r.source))).catch(e=>setError(message(e)))}}><option value="">Open saved program…</option>{programs.map(p=><option key={p}>{p}</option>)}</select>
 <hr/><h3 className="h6">Loaded program inputs · C{context}</h3>{loaded?<><p className="small text-secondary">{loaded.source===source?'Draft matches loaded program.':'The loaded program differs from the editor draft.'}</p>
 <div className="df-named-inputs">{loaded.inputs.map(v=><label key={v.name}>{v.name} <small>{v.type}</small><input aria-label={`Input ${v.name}`} className="form-control form-control-sm" value={values[v.name]??''} onChange={e=>setValues({...values,[v.name]:e.target.value})}/></label>)}</div>
 <button className="btn btn-outline-primary w-100 mt-2" disabled={disabled||frame?.snapshot.debug.halted} onClick={()=>void supply()}>Supply named inputs</button><p className="small text-secondary mt-2">Then advance cycles and poll the result. Cancel a closed context before reusing it.</p></>:<p className="small text-secondary">Compile and load to bind named values to graph ports.</p>}
 </div>
}
const kinds=['','operand commit','issue','unit completion','route delivery','output accepted','cancel','stale discard'];
export function Debugger({snapshot:s,program,selected,context,locked,invoke}:{snapshot:Snapshot;program:Program|null;selected:number;context:number;locked:boolean;invoke:(o:Operation)=>Promise<void>}){
 const [mask,setMask]=useState(1);const [filter,setFilter]=useState(false);const [anyContext,setAnyContext]=useState(true);const d=s.debug;
 const eventList=d.events.filter(e=>!filter||e.token.node===selected&&e.token.context===context);
 const configure=(resume=false,clear=false)=>invoke({kind:'debug',debug:{mask,node:selected,context:anyContext?255:context,resume,clear}});
 return <section className="df-panel df-debugger"><div className="df-panel-heading"><h2>Breakpoints & event trace</h2><span>{d.halted?`HALTED · cycle ${d.stopCycle}`:'Ready for explicit ticks'}</span></div>
 {d.halted&&<div className="alert alert-warning small" role="status">Stopped after a clock edge: {[d.reason&1?'node issued':'',d.reason&2?'completion queue was full':'',d.reason&4?'stale work discarded':''].filter(Boolean).join(', ')}. Resume explicitly to continue.</div>}
 <div className="df-debug-controls"><label>Condition<select aria-label="Breakpoint condition" className="form-select form-select-sm" value={mask} onChange={e=>setMask(Number(e.target.value))}><option value="0">Disarmed</option><option value="1">Selected node issues</option><option value="2">Completion queue full</option><option value="4">Stale work discarded</option></select></label><span className="small">N{selected} {program?.nodes.find(n=>n.node===selected)?.name??''}</span><label className="small"><input type="checkbox" checked={anyContext} onChange={e=>setAnyContext(e.target.checked)}/> Any context</label>
 <button className="btn btn-sm btn-outline-dark" disabled={locked} onClick={()=>void configure()}>Apply breakpoint</button><button className="btn btn-sm btn-dark" disabled={locked||!d.halted} onClick={()=>void invoke({kind:'debug',debug:{mask:d.mask,node:d.node,context:d.context,resume:true}})}>Resume execution</button><button className="btn btn-sm btn-outline-secondary" disabled={locked} onClick={()=>void invoke({kind:'debug',debug:{mask:d.mask,node:d.node,context:d.context,clear:true}})}>Clear trace</button></div>
 <p className="small text-secondary mt-2">Armed mask {d.mask} · node {d.node===255?'any':d.node} · context {d.context===255?'any':d.context}. Resume preserves the armed predicate; a persistent condition can stop again.</p>
 {d.dropped>0?<div className="alert alert-warning small" role="status">Incomplete trace: {d.dropped} events were not recorded because of simultaneous events or full storage.</div>:<p className="small text-success">No recorded event losses since the last clear.</p>}
 <div className="d-flex justify-content-between small mb-2"><span>{d.events.length} / 32 records · {s.source==='serial'?'physical event RAM':'model event log'}</span><label><input type="checkbox" checked={filter} onChange={e=>setFilter(e.target.checked)}/> Selected node and context only</label></div>
 <div className="df-trace-scroll"><table className="table table-sm"><thead><tr><th>Cycle</th><th>Event</th><th>Context / epoch</th><th>Node / producer</th><th>Value</th></tr></thead><tbody>{eventList.map((e,n)=><tr key={n} className={e.kind===2?'table-info':''}><td>{e.cycle}</td><td>{kinds[e.kind]}</td><td>C{e.token.context} / E{e.token.epoch}</td><td>N{e.token.node} / {e.token.producer} {program?.nodes.find(v=>v.node===e.token.node)?.name}</td><td>{e.kind===6?'—':valueText(e.token.value)}</td></tr>)}</tbody></table></div>
 <p className="small text-secondary mb-0">Rows are captured events. Missing cycles are not synthesized. Cancellation and output polling can occur without an enabled tick.</p>
 </section>
}
